# .cargo/config.toml

[build]
target = "x86_64-segfaultylogic.json"

[unstable]
# Включаем build-std
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-segfaultylogic]
rustflags = [
  "-C", "link-arg=-Tlinker.ld",
  "-C", "relocation-model=pic",
]